### PR TITLE
Allow whitelist module in sentry

### PR DESCRIPTION
**Pull request by Micheal-Cini**
is there a code I can edit to allow the whitelist module to work in the sentry

### CODE REVIEW

**Comment by Geforce132** [comment]
The whitelist module _can_ be inserted into the sentry. Simply right-click the turret while holding the module to insert it. If that doesn't work, be sure that you're using the latest version of SecurityCraft.

**Comment by Micheal-Cini** [comment]
Its it an option for 1.7.10?

**Comment by Micheal-Cini** [comment]
oh nvm I wasn't on the newest version, Thank you!

**Comment by bl4ckscor3** [comment]
Next time, create an issue for this and not a pull requerst. Thank you.

**Pull request closed without merging**
