### PR TITLE
Wire cutters can now deactivate cage traps

### PR DESCRIPTION
**Pull request by scmcgowen**
I just added a few lines that let other players deactivate cage traps (1.12.2 only atm)

### CODE REVIEW

**Comment by scmcgowen** [comment]
newer versions coming soon unless you get to it first

**Comment by bl4ckscor3** [comment]
1. Please edit the relevant file instead of adding one in a completely random location
2. Don't feel obligated to create pull requests for other versions. I will take care of them after I merge a pull request. If there are 4 pull requests for the same feature for each version, but the pull request gets denied, we have 3 useless pull requests where the work put into them was for nothing.

**Comment by scmcgowen** [comment]
Oof. Didn’t realize it placed it in the wrong location sorry!

**Comment by bl4ckscor3** [comment]
Your code doesn't compile. I don't see a reason why I should put in the effort in properly reviewing this pull request, when you didn't even put in the effort to check if your code compile, let alone to test it ingame. Apart from excess empty lines, and some other minor formatting errors, I can see a couple major gameplay issues with your code:
1. Rightclicking a deactivated cage trap will continue to damage the wire cutters, despite the cage trap already being deactivated.
2. Players in creative mode will still have their wire cutters be damaged. This is inconsistent with vanilla behavior, where items do not get damaged in creative mode.
3. There is no way to reactivate the cage trap (no, the Universal Block Modifier cannot do it).

As stated above, I won't properly review this pull request because you didn't even do the bare minimum that you should have done.

**Pull request closed without merging**
