### PR TITLE
[WIP] Fix for sentry's head Y translation after exit

### PR DESCRIPTION
**Pull request by LorenaGdL**
Little graphic bug regarding sentries. If you set your sentry to agressive mode, it successfully animates upwards. However, if you exit the server and enter again, the sentry's head will be hidden because the Y translation is not saved, and so it seems the sentry is in either camouflage or idle mode. This does not affect operation, it still attacks mobs&players.

This PR is work in progress, because I'm having some trouble finding the ideal solution. I have two possible different approaches, both with its pros and cons

1. First solution would be to save head Y translation to NBT, as it's done with the head rotation
   - _Pros_: I'd say this would be the expected approach. It should have minimal performance impact
   - _Cons_: **it doesn't work**. Better said, I can't make it work, because I'm sure there's something I'm missing, but I truly can find the problem. Animation works fine when toggling mode, so renderer is correctly reading the `HEAD_TRANSLATION` at that time. But if you exit and enter the server, the head would be just hidden no matter what, so seems a problem while writing/reading to/from NBT. Also, I'm not sure if this fix is totally backwards compatible, since already created sentries wouldn't have the associated NBT tag, so they would be initially assigned the default value which may or may not be the correct one depending on their mode.

2. Second solution would involve no changes, just 4 new lines (ignore they're commented...) (https://github.com/LorenaGdL/SecurityCraft/blob/eaf0fa3afee11ddc7f12d23c5f5d370ce63c6921/src/main/java/net/geforcemods/securitycraft/entity/EntitySentry.java#L102-L105)

    - _Cons_: involves specifically checking for the issue (aggressive mode but head down) in each update, while it's a problem only present on init. So not efficient, though it's just a check...
    - _Pros_: simple and **it works**. Also, it would also prevent/fix an even rarer bug that could theoretically happen in solution 1 when you exit the server in the middle of the upwards animation, saving a half-way head Y position to NBT.

I'd appreciate if you could throw some light on this... Please, don't hate me too much

### CODE REVIEW

**Comment by bl4ckscor3** [comment]
NBT is saved on the logical server. The animation only happens on the client (see `world.isRemote` check), hence the server does not have the proper rotation/translation/etc. value, resulting in it not being properly stored in NBT. Upon rejoining, the server tells the client about this incorrect value and the client shows the sentry retracted.

**Comment by LorenaGdL** [comment]
Got it, thanks for the explanation and apologies for my dumbness...
It seems needed changes for saving translation to NBT would do more harm than good, so updated the PR to provide the simple solution in which it's the client the one doing a simple extra check.

Anyway, if you don't think this is the right approach, feel free to close this.

**Comment by bl4ckscor3** [comment]
> apologies for my dumbness...
No worries, PRs can be discussed to make them the best they can be.
> Anyway, if you don't think this is the right approach, feel free to close this.
It sure isn't the best approach, but the one with the least impact, so it's better than nothing :) I'll take a closer look at the changes at some point in the next few days and test them out to see if there's any unexpected behavior.

**Comment by bl4ckscor3** [comment]
Looks good, also works when switching dimensions. Thanks!

**Comment by bl4ckscor3** [comment]
Looks good, also works when switching dimensions. Thanks!

**Pull request merged**
